services:
  sqlserver:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - ./volumes/database/data:/var/opt/mssql/data
      - ./volumes/database/log:/var/opt/mssql/log
      - ./volumes/database/secrets:/var/opt/mssql/secrets
    networks:
      - acflix-net
  minio:
    image: minio/minio
    container_name: minio-acflix
    ports:
        - 9000:9000
        - 9001:9001
    volumes:
        - ./volumes/storage:/data
    environment:
        MINIO_ROOT_USER: acflixminio
        MINIO_ROOT_PASSWORD: acflixminio  
    command: server --console-address ":9001" /data
    networks:
      - acflix-net
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  acflix-net:
    driver: host
